#ifndef UCDFS_TELEMETRY_TASK_PRIORITIES_H
#define UCDFS_TELEMETRY_TASK_PRIORITIES_H

#define PRIORITY_TASK_TELEMETRY 10
#define PRIORITY_TASK_GPS 2
#define PRIORITY_TASK_ACCELEROMETER 1
#define PRIORITY_TASK_BRAKE_TEMPERATURE 1
#define PRIORITY_TASK_NEXTION_DISPLAY 1
#define PRIORITY_TASK_TEMPERATURE 1
#define PRIORITY_TASK_WHEEL_SPEED 1
#define PRIORITY_TASK_WIFI_STRENGTH 1
#define PRIORITY_TASK_STATUS_DISPLAY 0
#define PRIORITY_TASK_STATUS_LED 0

#endif //UCDFS_TELEMETRY_TASK_PRIORITIES_H
